//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITestDocumentCreator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PrintStrings_pt_br {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrintStrings_pt_br() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APITestDocumentCreator.Resources", typeof(PrintStrings_pt_br).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Criada estrutura básica no seguinte caminho: {0}.
        /// </summary>
        internal static string BasicApplicationStructureCreated {
            get {
                return ResourceManager.GetString("BasicApplicationStructureCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[INFO] Nesta etapa a aplicação vai verificar se as pastas e arquivos de base já foram criados ou precisam ser criados.
        ///.
        /// </summary>
        internal static string BasicApplicationStructureDescription {
            get {
                return ResourceManager.GetString("BasicApplicationStructureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Estrutura básica do arquivo já existe! Não precisa criar-la. O caminho é {0}.
        /// </summary>
        internal static string BasicApplicationStructureExists {
            get {
                return ResourceManager.GetString("BasicApplicationStructureExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Arquivo de destaques &apos;{0}.txt&apos; foi criado dentro da pasta..
        /// </summary>
        internal static string BasicApplicationStructureHighlightCreated {
            get {
                return ResourceManager.GetString("BasicApplicationStructureHighlightCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Arquivo de destaque &apos;{0}.txt&apos; foi criado dentro da pasta, com um exemplo dentro..
        /// </summary>
        internal static string BasicApplicationStructureHighlightExampleCreated {
            get {
                return ResourceManager.GetString("BasicApplicationStructureHighlightExampleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Arquivo de destaque já existe, por favor coloque os nomes dos parametros nele caso deseja dar destaque em algum parametro!.
        /// </summary>
        internal static string BasicApplicationStructureHighlightExists {
            get {
                return ResourceManager.GetString("BasicApplicationStructureHighlightExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Arquivo de entrada &apos;{0}.txt&apos; foi criado dentro da pasta..
        /// </summary>
        internal static string BasicApplicationStructureInputCreated {
            get {
                return ResourceManager.GetString("BasicApplicationStructureInputCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Arquivo de entrada &apos;{0}.txt&apos; foi criado dentro da pasta, com um exemplo dentro..
        /// </summary>
        internal static string BasicApplicationStructureInputExampleCreated {
            get {
                return ResourceManager.GetString("BasicApplicationStructureInputExampleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Arquivo de entrada já existe, por favor verifique os dados nele!.
        /// </summary>
        internal static string BasicApplicationStructureInputExists {
            get {
                return ResourceManager.GetString("BasicApplicationStructureInputExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Arquivo de seção &apos;{0}.txt&apos; foi criado dentro da pasta..
        /// </summary>
        internal static string BasicApplicationStructureSectionCreated {
            get {
                return ResourceManager.GetString("BasicApplicationStructureSectionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Arquivo de seção &apos;{0}.txt&apos; foi criado dentro da pasta, com um exemplo dentro..
        /// </summary>
        internal static string BasicApplicationStructureSectionExampleCreated {
            get {
                return ResourceManager.GetString("BasicApplicationStructureSectionExampleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Arquivo de seção já existe, por favor revise se o arquivo está no padrão correto!.
        /// </summary>
        internal static string BasicApplicationStructureSectionExists {
            get {
                return ResourceManager.GetString("BasicApplicationStructureSectionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      ESTRUTURA BÁSICA DA APLICAÇÃO
        ///.
        /// </summary>
        internal static string BasicApplicationStructureTitle {
            get {
                return ResourceManager.GetString("BasicApplicationStructureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Esta é uma etapa importante da aplicação, onde é explicado como o padrão dos 4 tipos de arquivos de entrada são, preste atenção aos detalhes abaixo e não se esqueça de que cada campo é separado por ponto e vírgula (;).
        ///.
        /// </summary>
        internal static string DataPatternExplanationDescription {
            get {
                return ResourceManager.GetString("DataPatternExplanationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Aqui o objetivo é ler os parametros que você deseja que seja destacado em amarelo, esta parte é completamente opcional, mas se deseja destacar qualquer coisa no JSON, alguns campos são obrigatórios.
        ///.
        /// </summary>
        internal static string DataPatternExplanationHighlightParametersDescription {
            get {
                return ResourceManager.GetString("DataPatternExplanationHighlightParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) NOME DO PARÂMETRO*: Nome do parâmetro dentro do JSON (pode ser na requisição ou resposta)..
        /// </summary>
        internal static string DataPatternExplanationHighlightParametersDescriptionParameterName {
            get {
                return ResourceManager.GetString("DataPatternExplanationHighlightParametersDescriptionParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) REFERÊNCIA DE NOME DO PARÂMETRO: Se o parâmetro que vai ser destacado está dentro de uma lista no JSON com múltiplos objetos, por exemplo, você pode definir o nome do parâmetro que será usado como referência..
        /// </summary>
        internal static string DataPatternExplanationHighlightParametersDescriptionParameterNameReference {
            get {
                return ResourceManager.GetString("DataPatternExplanationHighlightParametersDescriptionParameterNameReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4) REFERÊNCIA DE VALOR DO PARÂMETRO: Se o parâmetro que vai ser destacado está dentro de uma lista no JSON com múltiplos objetos, por exemplo, você pode definir o valor do parâmetro que será usado como referência..
        /// </summary>
        internal static string DataPatternExplanationHighlightParametersDescriptionParameterValueReference {
            get {
                return ResourceManager.GetString("DataPatternExplanationHighlightParametersDescriptionParameterValueReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBS: Se você deseja destacar um parâmetro baseado em outro parâmetro / valor como referência, todos os campos são obrigatórios!.
        /// </summary>
        internal static string DataPatternExplanationHighlightParametersDescriptionReminder {
            get {
                return ResourceManager.GetString("DataPatternExplanationHighlightParametersDescriptionReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) REFERÊNCIA DE NÚMERO DO SEÇÃO: Se deseja destacar um parâmetro somente em uma seção específica, preeencha somente somente este campo de referência..
        /// </summary>
        internal static string DataPatternExplanationHighlightParametersDescriptionSectionNumberReference {
            get {
                return ResourceManager.GetString("DataPatternExplanationHighlightParametersDescriptionSectionNumberReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Este é o arquivo principal da aplicação, aqui é onde os logs de todas as requisições / respostas da API devem ser armazenados.
        ///.
        /// </summary>
        internal static string DataPatternExplanationInputDataDescription {
            get {
                return ResourceManager.GetString("DataPatternExplanationInputDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) NOME DO MÉTODO*: Nome do endpoint da API onde vai aparecer no documento junto com sua respectiva requisição e resposta..
        /// </summary>
        internal static string DataPatternExplanationInputDataDescriptionMethodName {
            get {
                return ResourceManager.GetString("DataPatternExplanationInputDataDescriptionMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4) REQUISIÇÃO*: JSON usado na requisição da API (não precisa de pré-formatação)..
        /// </summary>
        internal static string DataPatternExplanationInputDataDescriptionRequest {
            get {
                return ResourceManager.GetString("DataPatternExplanationInputDataDescriptionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5) RESPOSTA*: JSON recebido na repossta da API (não precisa de pré-formatação)..
        /// </summary>
        internal static string DataPatternExplanationInputDataDescriptionResponse {
            get {
                return ResourceManager.GetString("DataPatternExplanationInputDataDescriptionResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) NÚMERO DA SEÇÃO*: Número da seção do qual todas as entradas serão apresentadas no documento, se a seção tiver mais de uma linha de entrada, coloque o mesmo número mas escreva na ordem em que deve aparecer..
        /// </summary>
        internal static string DataPatternExplanationInputDataDescriptionSectionNumber {
            get {
                return ResourceManager.GetString("DataPatternExplanationInputDataDescriptionSectionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) URL*: URL usada na requisição para a API..
        /// </summary>
        internal static string DataPatternExplanationInputDataDescriptionURL {
            get {
                return ResourceManager.GetString("DataPatternExplanationInputDataDescriptionURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Essa é etapa é completamente opcional, porém se deseja colocar algumas imagens em cada seção do documento, um padrão deve ser seguido.
        ///.
        /// </summary>
        internal static string DataPatternExplanationPicturesDescription {
            get {
                return ResourceManager.GetString("DataPatternExplanationPicturesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOME DA IMAGEM: Cada imagem deve ser declarada através da indicação da sua seção e ordem, um exemplo é &apos;2_1.png&apos; onde esta imagem está na seção 2 e será a primeira imagem mostrada..
        /// </summary>
        internal static string DataPatternExplanationPicturesImageName {
            get {
                return ResourceManager.GetString("DataPatternExplanationPicturesImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      PADRÃO DA PASTA PICTURES.
        /// </summary>
        internal static string DataPatternExplanationPicturesTitle {
            get {
                return ResourceManager.GetString("DataPatternExplanationPicturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Neste arquivo você deve preenche-lo com todas as informações referente aos setores do documento.
        ///.
        /// </summary>
        internal static string DataPatternExplanationSectionInformationDescription {
            get {
                return ResourceManager.GetString("DataPatternExplanationSectionInformationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) DESCRIÇÃO: Um texto que deve brevemente explicar o que aconteceu nesse setor..
        /// </summary>
        internal static string DataPatternExplanationSectionInformationDescriptionSection {
            get {
                return ResourceManager.GetString("DataPatternExplanationSectionInformationDescriptionSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) NOME DA SEÇÃO*: Nome usado para definir a seção..
        /// </summary>
        internal static string DataPatternExplanationSectionInformationDescriptionSectionName {
            get {
                return ResourceManager.GetString("DataPatternExplanationSectionInformationDescriptionSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) NÚMERO DA SEÇÃO*: Número da seção a ser apresentado no documento..
        /// </summary>
        internal static string DataPatternExplanationSectionInformationDescriptionSectionNumber {
            get {
                return ResourceManager.GetString("DataPatternExplanationSectionInformationDescriptionSectionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    ARQUIVOS DE DADOS - EXPLICAÇÃO DO PADRÃO
        ///.
        /// </summary>
        internal static string DataPatternExplanationTitle {
            get {
                return ResourceManager.GetString("DataPatternExplanationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&gt; Antes de continuar com a validação de todos os quatro arquivos, revise se os dados inseridos estão de acordo com seu respectivo padrão.
        ///
        ///Opção: .
        /// </summary>
        internal static string DataPatternValidationQuestion {
            get {
                return ResourceManager.GetString("DataPatternValidationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Digite &apos;1&apos; se estiver OK
        ///- Digite &apos;2&apos; para sair da aplicação
        ///
        ///Opção: .
        /// </summary>
        internal static string DataPatternValidationQuestionOptions {
            get {
                return ResourceManager.GetString("DataPatternValidationQuestionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Esta etapa é para colocar algumas informações sobre as propriedades do documento.
        ///.
        /// </summary>
        internal static string DocumentBasicInformationDescription {
            get {
                return ResourceManager.GetString("DocumentBasicInformationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           PROPRIEDADES DO DOCUMENTO
        ///.
        /// </summary>
        internal static string DocumentBasicInformationTitle {
            get {
                return ResourceManager.GetString("DocumentBasicInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Qual é o título do documento? (O título também vai ser o nome do arquivo final)
        ///Título: .
        /// </summary>
        internal static string DocumentBasicInformationTitleInput {
            get {
                return ResourceManager.GetString("DocumentBasicInformationTitleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[INFO] O título não pode ser vazio! 
        ///Por favor insira um novo título: .
        /// </summary>
        internal static string DocumentBasicInformationTitleInputEmptyValidation {
            get {
                return ResourceManager.GetString("DocumentBasicInformationTitleInputEmptyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] O texto do título só pode conter o seguinte:
        ///- NÚMEROS (0-9)
        ///- CARACTERES ALFABÉTICOS  (A-Z)
        ///- UNDERLINE (_)
        ///- HÍFEN (-)
        ///
        ///Por favor insira um novo título: .
        /// </summary>
        internal static string DocumentBasicInformationTitleInputRegexValidation {
            get {
                return ResourceManager.GetString("DocumentBasicInformationTitleInputRegexValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///[INFO] Saindo da aplicação....
        /// </summary>
        internal static string ExitingApplication {
            get {
                return ResourceManager.GetString("ExitingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Se é sua primeira vez usando essa aplicação, é possível criar um documento de exemplo para ver como funciona, você deseja prosseguir com o exemplo?
        ///.
        /// </summary>
        internal static string InformationExampleDocumentation {
            get {
                return ResourceManager.GetString("InformationExampleDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[INFO] Aqui a aplicação vai realizar algumas validações em cada arquivo para verificar se está de acordo com o esperado.
        ///.
        /// </summary>
        internal static string InputFilesValidationDescription {
            get {
                return ResourceManager.GetString("InputFilesValidationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[ERROR] Algumas validações falharam, ajuste cada erro antes de reiniciar a aplicação!.
        /// </summary>
        internal static string InputFilesValidationFailed {
            get {
                return ResourceManager.GetString("InputFilesValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR | LINHA {0}] O campo &apos;Valor do Parâmetro&apos; não pode ser vazio se o campo &apos;Nome do Parâmetro&apos; estiver preenchido!.
        /// </summary>
        internal static string InputFilesValidationHighlightParametersTest1 {
            get {
                return ResourceManager.GetString("InputFilesValidationHighlightParametersTest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR | LINHA {0}] Um dos campos desta linha está vazio!.
        /// </summary>
        internal static string InputFilesValidationInputDataTest1 {
            get {
                return ResourceManager.GetString("InputFilesValidationInputDataTest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR | LINHA {0}] O primeiro campo da linha deve ser um NÚMERO INTEIRO!.
        /// </summary>
        internal static string InputFilesValidationInputDataTest2 {
            get {
                return ResourceManager.GetString("InputFilesValidationInputDataTest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[INFO] Todas as validações estão OK e você pode proceder com a criação do documento!
        ///.
        /// </summary>
        internal static string InputFilesValidationPassed {
            get {
                return ResourceManager.GetString("InputFilesValidationPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Nada foi encontrado no diretório &apos;Pictures&apos;..
        /// </summary>
        internal static string InputFilesValidationPicturesFolderCounterEqualZero {
            get {
                return ResourceManager.GetString("InputFilesValidationPicturesFolderCounterEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] {0} arquivo(s) encontrado(s)..
        /// </summary>
        internal static string InputFilesValidationPicturesFolderCounterMoreThanZero {
            get {
                return ResourceManager.GetString("InputFilesValidationPicturesFolderCounterMoreThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR | LINHA {0}] Número de seção e / ou título da seção estão vázios e ambos são necessários para a aplicação!.
        /// </summary>
        internal static string InputFilesValidationSectionInformationTest1 {
            get {
                return ResourceManager.GetString("InputFilesValidationSectionInformationTest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR | LINHA {0}] O primeiro campo da linha deve ser um NÚMERO INTEIRO!.
        /// </summary>
        internal static string InputFilesValidationSectionInformationTest2 {
            get {
                return ResourceManager.GetString("InputFilesValidationSectionInformationTest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to          VALIDAÇÃO DOS ARQUIVOS DE ENTRADA
        ///.
        /// </summary>
        internal static string InputFilesValidationTitle {
            get {
                return ResourceManager.GetString("InputFilesValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressione alguma tecla para iniciar a criação...
        ///.
        /// </summary>
        internal static string PressAnyKeyStartCreation {
            get {
                return ResourceManager.GetString("PressAnyKeyStartCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Pressione alguma tecla para proceder....
        /// </summary>
        internal static string PressAnyKeyToProceed {
            get {
                return ResourceManager.GetString("PressAnyKeyToProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR]: Ocorreu um erro! Veja os detalhes abaixo: 
        ///{0}.
        /// </summary>
        internal static string PrintGenericErrorException {
            get {
                return ResourceManager.GetString("PrintGenericErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///* - Campo obrigatório..
        /// </summary>
        internal static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[INFO] Você escolheu a língua Português Brasileiro!
        ///.
        /// </summary>
        internal static string UserDecisionApplicationLanguage {
            get {
                return ResourceManager.GetString("UserDecisionApplicationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Aperte &apos;1&apos; para criar o exemplo
        ///- Aperte &apos;2&apos; para customizar os dados de entrada
        ///
        ///Opção: .
        /// </summary>
        internal static string UserDecisionExampleDocumentation {
            get {
                return ResourceManager.GetString("UserDecisionExampleDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///[INFO] Usuário escolheu proceder com o exemplo!
        ///.
        /// </summary>
        internal static string UserDecisionOptionOneExampleDocumentation {
            get {
                return ResourceManager.GetString("UserDecisionOptionOneExampleDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///[INFO] Usuário vai colocar seus próprios dados!
        ///.
        /// </summary>
        internal static string UserDecisionOptionTwoExampleDocumentation {
            get {
                return ResourceManager.GetString("UserDecisionOptionTwoExampleDocumentation", resourceCulture);
            }
        }
    }
}
