//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITestDocumentCreator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PrintStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrintStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APITestDocumentCreator.Resources.PrintStrings", typeof(PrintStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Creating basic folder strucutre in the following path: {0}.
        /// </summary>
        internal static string BasicApplicationStructureCreated {
            get {
                return ResourceManager.GetString("BasicApplicationStructureCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## In this step the application will check if the base folders and files are already created or need creation.
        ///.
        /// </summary>
        internal static string BasicApplicationStructureDescription {
            get {
                return ResourceManager.GetString("BasicApplicationStructureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Basic folder structure already exists! No need for creation. The path is {0}.
        /// </summary>
        internal static string BasicApplicationStructureExists {
            get {
                return ResourceManager.GetString("BasicApplicationStructureExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Highlight file &apos;{0}.txt&apos; has been created inside the folder..
        /// </summary>
        internal static string BasicApplicationStructureHighlightCreated {
            get {
                return ResourceManager.GetString("BasicApplicationStructureHighlightCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Highlight file &apos;{0}.txt&apos; has been created inside the folder, with an example inside it..
        /// </summary>
        internal static string BasicApplicationStructureHighlightExampleCreated {
            get {
                return ResourceManager.GetString("BasicApplicationStructureHighlightExampleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Highlight file already exist, please put the parameter names on it if you wish to highlight any parameter!.
        /// </summary>
        internal static string BasicApplicationStructureHighlightExists {
            get {
                return ResourceManager.GetString("BasicApplicationStructureHighlightExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Input file &apos;{0}.txt&apos; has been created inside the folder..
        /// </summary>
        internal static string BasicApplicationStructureInputCreated {
            get {
                return ResourceManager.GetString("BasicApplicationStructureInputCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Input file &apos;{0}.txt&apos; has been created inside the folder, with an example inside it..
        /// </summary>
        internal static string BasicApplicationStructureInputExampleCreated {
            get {
                return ResourceManager.GetString("BasicApplicationStructureInputExampleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Input file already exist, please check your data inside it!.
        /// </summary>
        internal static string BasicApplicationStructureInputExists {
            get {
                return ResourceManager.GetString("BasicApplicationStructureInputExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Section file &apos;{0}.txt&apos; has been created inside the folder..
        /// </summary>
        internal static string BasicApplicationStructureSectionCreated {
            get {
                return ResourceManager.GetString("BasicApplicationStructureSectionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Section file &apos;{0}.txt&apos; has been created inside the folder, with an example inside it..
        /// </summary>
        internal static string BasicApplicationStructureSectionExampleCreated {
            get {
                return ResourceManager.GetString("BasicApplicationStructureSectionExampleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Section data file already exist, please review if the file is in the correct pattern!.
        /// </summary>
        internal static string BasicApplicationStructureSectionExists {
            get {
                return ResourceManager.GetString("BasicApplicationStructureSectionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      BASIC APPLICATION STRUCTURE
        ///.
        /// </summary>
        internal static string BasicApplicationStructureTitle {
            get {
                return ResourceManager.GetString("BasicApplicationStructureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## This is an important step of the application, where is explained how the 4 types of input files patterns are, pay attention to the details bellow and don&apos;t forget that each field in the text files are separated with a semi-colon (;)..
        /// </summary>
        internal static string DataPatternExplanationDescription {
            get {
                return ResourceManager.GetString("DataPatternExplanationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Here the objective is to read the parameters that you want to be highlighted in yellow, this part is completely optional, but if you want to highlight anything in the JSON, some fields are required.
        ///.
        /// </summary>
        internal static string DataPatternExplanationHighlightParametersDescription {
            get {
                return ResourceManager.GetString("DataPatternExplanationHighlightParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) PARAMETER NAME*: Name of the parameter inside the JSON (can be in the request or response)..
        /// </summary>
        internal static string DataPatternExplanationHighlightParametersDescriptionParameterName {
            get {
                return ResourceManager.GetString("DataPatternExplanationHighlightParametersDescriptionParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) PARAMETER NAME REFERENCE: If the parameter that will be highlighted is inside an array in the JSON with multiple objects, an example, you can define the name of the parameter that will be used as reference..
        /// </summary>
        internal static string DataPatternExplanationHighlightParametersDescriptionParameterNameReference {
            get {
                return ResourceManager.GetString("DataPatternExplanationHighlightParametersDescriptionParameterNameReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4) PARAMETER VALUE REFERENCE: If the parameter that will be highlighted is inside an array in the JSON with multiple objects, an example, you can define the value of the parameter that will be used as reference..
        /// </summary>
        internal static string DataPatternExplanationHighlightParametersDescriptionParameterValueReference {
            get {
                return ResourceManager.GetString("DataPatternExplanationHighlightParametersDescriptionParameterValueReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PS: If you wanna highlight a parameter based on another parameter / value reference, all fields need to be filled!.
        /// </summary>
        internal static string DataPatternExplanationHighlightParametersDescriptionReminder {
            get {
                return ResourceManager.GetString("DataPatternExplanationHighlightParametersDescriptionReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) SECTION NUMBER REFERENCE: If you want to highlight a parameter only in a specific sector, fill only this reference field..
        /// </summary>
        internal static string DataPatternExplanationHighlightParametersDescriptionSectionNumberReference {
            get {
                return ResourceManager.GetString("DataPatternExplanationHighlightParametersDescriptionSectionNumberReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## The main file of the application, this is where all API request / response logs should be stored.
        ///.
        /// </summary>
        internal static string DataPatternExplanationInputDataDescription {
            get {
                return ResourceManager.GetString("DataPatternExplanationInputDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) METHOD NAME*: Name of the API endpoint that will appear in the document close to it&apos;s respective JSON request and response..
        /// </summary>
        internal static string DataPatternExplanationInputDataDescriptionMethodName {
            get {
                return ResourceManager.GetString("DataPatternExplanationInputDataDescriptionMethodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4) REQUEST*: JSON used in the request (don&apos;t need pre-formatting)..
        /// </summary>
        internal static string DataPatternExplanationInputDataDescriptionRequest {
            get {
                return ResourceManager.GetString("DataPatternExplanationInputDataDescriptionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5) RESPONSE*: JSON received in the response (don&apos;t need pre-formatting)..
        /// </summary>
        internal static string DataPatternExplanationInputDataDescriptionResponse {
            get {
                return ResourceManager.GetString("DataPatternExplanationInputDataDescriptionResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) SECTION NUMBER*: Section number in which all the input will be showed in the document, if the section has more than one input line, apply the same number but write in the order of appeareance..
        /// </summary>
        internal static string DataPatternExplanationInputDataDescriptionSectionNumber {
            get {
                return ResourceManager.GetString("DataPatternExplanationInputDataDescriptionSectionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) URL*: URL used in the request to the API..
        /// </summary>
        internal static string DataPatternExplanationInputDataDescriptionURL {
            get {
                return ResourceManager.GetString("DataPatternExplanationInputDataDescriptionURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## This step is completely optional, but if you want to put some images on each section of the document, a pattern must be followed.
        ///.
        /// </summary>
        internal static string DataPatternExplanationPicturesDescription {
            get {
                return ResourceManager.GetString("DataPatternExplanationPicturesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGE NAME: Each image must be declare by indicating its section and order, an example is &apos;2_1.png&apos; where this image is in sector 2 and is the first image to be showed..
        /// </summary>
        internal static string DataPatternExplanationPicturesImageName {
            get {
                return ResourceManager.GetString("DataPatternExplanationPicturesImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      PICTURES FOLDER PATTERN
        ///.
        /// </summary>
        internal static string DataPatternExplanationPicturesTitle {
            get {
                return ResourceManager.GetString("DataPatternExplanationPicturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## In this file you will fill all informations about the sectors of the document.
        ///.
        /// </summary>
        internal static string DataPatternExplanationSectionInformationDescription {
            get {
                return ResourceManager.GetString("DataPatternExplanationSectionInformationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) DESCRIPTION: A text that should briefly explain what happened in the sector..
        /// </summary>
        internal static string DataPatternExplanationSectionInformationDescriptionSection {
            get {
                return ResourceManager.GetString("DataPatternExplanationSectionInformationDescriptionSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) SECTION NAME*: The name used to define the section..
        /// </summary>
        internal static string DataPatternExplanationSectionInformationDescriptionSectionName {
            get {
                return ResourceManager.GetString("DataPatternExplanationSectionInformationDescriptionSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) SECTION NUMBER*: Number of the section that will be showed in the document..
        /// </summary>
        internal static string DataPatternExplanationSectionInformationDescriptionSectionNumber {
            get {
                return ResourceManager.GetString("DataPatternExplanationSectionInformationDescriptionSectionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    DATA FILES - PATTERN EXPLANATION
        ///.
        /// </summary>
        internal static string DataPatternExplanationTitle {
            get {
                return ResourceManager.GetString("DataPatternExplanationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&gt; Before we continue with the validation of all files, review if the data inside the files is following its respective pattern.
        ///
        ///Option: .
        /// </summary>
        internal static string DataPatternValidationQuestion {
            get {
                return ResourceManager.GetString("DataPatternValidationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Type &apos;1&apos; if it&apos;s OK
        ///- Type &apos;2&apos; to exit application
        ///
        ///Option: .
        /// </summary>
        internal static string DataPatternValidationQuestionOptions {
            get {
                return ResourceManager.GetString("DataPatternValidationQuestionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## This step is to input some informations about the properties of the document.
        ///.
        /// </summary>
        internal static string DocumentBasicInformationDescription {
            get {
                return ResourceManager.GetString("DocumentBasicInformationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           DOCUMENT PROPERTIES
        ///.
        /// </summary>
        internal static string DocumentBasicInformationTitle {
            get {
                return ResourceManager.GetString("DocumentBasicInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; What is the title of the document? (The title will be the result file name too)
        ///Title: .
        /// </summary>
        internal static string DocumentBasicInformationTitleInput {
            get {
                return ResourceManager.GetString("DocumentBasicInformationTitleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[INFO] The title can&apos;t be empty!
        ///Please insert a new title: .
        /// </summary>
        internal static string DocumentBasicInformationTitleInputEmptyValidation {
            get {
                return ResourceManager.GetString("DocumentBasicInformationTitleInputEmptyValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[INFO] The title text can only contain the following:
        ///- NUMBERS (0-9)
        ///- ALPHABETICAL CHARACTERS (A-Z)
        ///- UNDERLINE (_)
        ///- HYPHEN (-)
        ///
        ///Please insert a new title: .
        /// </summary>
        internal static string DocumentBasicInformationTitleInputRegexValidation {
            get {
                return ResourceManager.GetString("DocumentBasicInformationTitleInputRegexValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Document created in the following path: {0}\{1}.docx.
        /// </summary>
        internal static string DocumentCreatedConfirmation {
            get {
                return ResourceManager.GetString("DocumentCreatedConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Starting creation process..
        /// </summary>
        internal static string DocumentCreationAlert {
            get {
                return ResourceManager.GetString("DocumentCreationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           DOCUMENT CREATION
        ///.
        /// </summary>
        internal static string DocumentCreationTitle {
            get {
                return ResourceManager.GetString("DocumentCreationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///[INFO] Exiting application....
        /// </summary>
        internal static string ExitingApplication {
            get {
                return ResourceManager.GetString("ExitingApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] If is your first time using this application, it&apos;s possible to create an example document to see how it works, do you want to proceed with this example?.
        /// </summary>
        internal static string InformationExampleDocumentation {
            get {
                return ResourceManager.GetString("InformationExampleDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Here the application will make some validations on each file to verify if it follows what is expected.
        ///.
        /// </summary>
        internal static string InputFilesValidationDescription {
            get {
                return ResourceManager.GetString("InputFilesValidationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[ERROR] Some validations have failed, fix every error showed before and restart the application!.
        /// </summary>
        internal static string InputFilesValidationFailed {
            get {
                return ResourceManager.GetString("InputFilesValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR | LINE {0}] The field &apos;Parameter Value&apos; cannot be empty if the field &apos;Parameter Name&apos; is filled!.
        /// </summary>
        internal static string InputFilesValidationHighlightParametersTest1 {
            get {
                return ResourceManager.GetString("InputFilesValidationHighlightParametersTest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR | LINE {0}] One of the fields in this line are empty!.
        /// </summary>
        internal static string InputFilesValidationInputDataTest1 {
            get {
                return ResourceManager.GetString("InputFilesValidationInputDataTest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR | LINE {0}] The first field of the line must be a INTEGER NUMBER!.
        /// </summary>
        internal static string InputFilesValidationInputDataTest2 {
            get {
                return ResourceManager.GetString("InputFilesValidationInputDataTest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[INFO] All validations are OK and you can proceed with the creation of the document!
        ///.
        /// </summary>
        internal static string InputFilesValidationPassed {
            get {
                return ResourceManager.GetString("InputFilesValidationPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] Nothing was found in the &apos;Pictures&apos; folder!.
        /// </summary>
        internal static string InputFilesValidationPicturesFolderCounterEqualZero {
            get {
                return ResourceManager.GetString("InputFilesValidationPicturesFolderCounterEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INFO] {0} image(s) detected in the &apos;Pictures&apos; folder!.
        /// </summary>
        internal static string InputFilesValidationPicturesFolderCounterMoreThanZero {
            get {
                return ResourceManager.GetString("InputFilesValidationPicturesFolderCounterMoreThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[ERROR | LINE {0}] Section number and / or section title are empty and both are need for the application!.
        /// </summary>
        internal static string InputFilesValidationSectionInformationTest1 {
            get {
                return ResourceManager.GetString("InputFilesValidationSectionInformationTest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ERROR | LINE {0}] The first field of the line must be a INTEGER NUMBER!.
        /// </summary>
        internal static string InputFilesValidationSectionInformationTest2 {
            get {
                return ResourceManager.GetString("InputFilesValidationSectionInformationTest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         INPUT FILES VALIDATION
        ///.
        /// </summary>
        internal static string InputFilesValidationTitle {
            get {
                return ResourceManager.GetString("InputFilesValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string JSONDescriptionWord {
            get {
                return ResourceManager.GetString("JSONDescriptionWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string JSONRequisitionWord {
            get {
                return ResourceManager.GetString("JSONRequisitionWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        internal static string JSONResponseWord {
            get {
                return ResourceManager.GetString("JSONResponseWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to start creation...
        ///.
        /// </summary>
        internal static string PressAnyKeyStartCreation {
            get {
                return ResourceManager.GetString("PressAnyKeyStartCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to exit application....
        /// </summary>
        internal static string PressAnyKeyToExitApplication {
            get {
                return ResourceManager.GetString("PressAnyKeyToExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Press any key to proceed....
        /// </summary>
        internal static string PressAnyKeyToProceed {
            get {
                return ResourceManager.GetString("PressAnyKeyToProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[ERROR]: An error has occurred! See details below: 
        ///{0}.
        /// </summary>
        internal static string PrintGenericErrorException {
            get {
                return ResourceManager.GetString("PrintGenericErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///* - Required field..
        /// </summary>
        internal static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///[INFO] You chose English language!
        ///.
        /// </summary>
        internal static string UserDecisionApplicationLanguage {
            get {
                return ResourceManager.GetString("UserDecisionApplicationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///- Type &apos;1&apos; to create example
        ///- Type &apos;2&apos; to customize input data
        ///
        ///Option: .
        /// </summary>
        internal static string UserDecisionExampleDocumentation {
            get {
                return ResourceManager.GetString("UserDecisionExampleDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///[INFO] User chose to proceed with example!
        ///.
        /// </summary>
        internal static string UserDecisionOptionOneExampleDocumentation {
            get {
                return ResourceManager.GetString("UserDecisionOptionOneExampleDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///[INFO] User will input it&apos;s own data!
        ///.
        /// </summary>
        internal static string UserDecisionOptionTwoExampleDocumentation {
            get {
                return ResourceManager.GetString("UserDecisionOptionTwoExampleDocumentation", resourceCulture);
            }
        }
    }
}
